### PR TITLE
Add Continuous Integration.

### LINKED ISSUE #15: Set up CI
E.g., copy stuff from UniMath/TypeTheory

### PR DESCRIPTION
**Pull request by m-lindgren**
Fixes #15.

Uses cache similar to UniMath and TypeTheory.

Builds each PR with Coq 8.16 and latest released version.

### CODE REVIEW

**Comment by m-lindgren** [comment]
@benediktahrens Do you know if there's some setting one needs to change for an action to trigger?

**Comment by benediktahrens** [comment]
> @benediktahrens Do you know if there's some setting one needs to change for an action to trigger?

I have checked the settings, they seem fine. Is it because the PR is marked as a draft?

**Comment by m-lindgren** [comment]
I had to make a commit using the webinterface "add your first workflow", then it worked. I found no way to enable it without doing it. So confusing.

**Comment by benediktahrens** [comment]
@m-lindgren : thanks a lot for setting this up!

**Pull request merged**
